# Generated by Django 4.2.3 on 2023-07-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="image", field=models.CharField(max_length=50),
        ),
    ]
