# Generated by Django 4.2.3 on 2023-07-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="image", field=models.CharField(max_length=200),
        ),
    ]
